import {
  index,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { users } from "./users";

export const securityAlertSeverityEnum = pgEnum("security_alert_severity", [
  "LOW",
  "MEDIUM",
  "HIGH",
  "CRITICAL",
]);

export const securityAlertStatusEnum = pgEnum("security_alert_status", [
  "OPEN",
  "ACKNOWLEDGED",
  "RESOLVED",
  "FALSE_POSITIVE",
]);

/**
 * Security Alerts table
 * Stores security alerts generated by risk scoring and anomaly detection
 */
export const securityAlerts = pgTable(
  "security_alerts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    adminId: uuid("admin_id").references(() => users.id, {
      onDelete: "set null",
    }), // Admin who triggered the alert (null for system alerts)
    severity: securityAlertSeverityEnum("severity").notNull(),
    status: securityAlertStatusEnum("status").notNull().default("OPEN"),
    title: text("title").notNull(),
    description: text("description").notNull(),
    alertType: text("alert_type").notNull(), // e.g., "RISK_SCORE", "SUSPICIOUS_LOGIN", "IP_REPUTATION"
    riskScore: text("risk_score"), // Risk score that triggered the alert (0-100)
    metadata: jsonb("metadata"), // Additional context (IP, user agent, action details, etc.)
    acknowledgedBy: uuid("acknowledged_by").references(() => users.id, {
      onDelete: "set null",
    }),
    acknowledgedAt: timestamp("acknowledged_at"),
    resolvedAt: timestamp("resolved_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    adminIdIdx: index("idx_security_alerts_adminId").on(table.adminId),
    severityIdx: index("idx_security_alerts_severity").on(table.severity),
    statusIdx: index("idx_security_alerts_status").on(table.status),
    alertTypeIdx: index("idx_security_alerts_alertType").on(table.alertType),
    createdAtIdx: index("idx_security_alerts_createdAt").on(table.createdAt),
  }),
);

export type SecurityAlert = typeof securityAlerts.$inferSelect;
export type NewSecurityAlert = typeof securityAlerts.$inferInsert;
